languageCode: en
defaultContentLanguage: en
baseURL: https://status.theforum365.com


params:
  categories:
    - name: Uncategorized
      untitled: true

  systems:
    - name: Forum
      description: The Main Forum
      category: Uncategorized

  dateFormat: January 2, 2006 at 3:04 PM
  shortDateFormat: 15:04 — Jan 2
  useLargeHeaderDesign: false

  incidentHistoryFormat: "yearly"
  disableIncidentHistory: false
  disableDarkMode: true
  useLogo: false
  logo: logo.png
  description: We continuously monitor the status of our services and if there are any interruptions, a note will be posted here.
  disableComplexCalculations: false

  # Incident posts shown
  # in one page
  #
  # NUMERIC; Default: `10`
  incidentPostsPerPage: 10
  brand: "#0a0c0f"
  ok: "#008000"
  disrupted: "#cc4400"
  down: "#e60000"
  notice: "#24478f"
  alwaysKeepBrandColor: true
  headerTextColor: white
  googleAnalytics: UA-00000000-1

theme: cstate

preserveTaxonomyNames: true

taxonomies:
  affected: affected

outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg

outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
